language: python
sudo: false
python:
  - "2.6"
  - "2.7"
before_install:
    - pip install pyserial coveralls
install: pip install -q -e .
script: python setup.py test
after_success:
  - coverage run --source=openxc setup.py test
  - coveralls
