language: python
python:
  - "2.6"
  - "2.7"
before_install:
    - pip install pyserial
    - pip install coveralls
script: python setup.py test
after_success:
  - coverage run --source=openxc setup.py test
  - coveralls
